### ISSUE TITLE
Invalid Metadata on mirror creation

### ISSUE THREAD

**Issue by renefritze** [montag451/pypi-mirror#10]
I have a problem with a [specific package](https://github.com/life4/vaa). If a mirror is to be created from including that file I get an error.
To reproduce:
```
pip download vaa==0.2.1 -d downloads  && pypi-mirror create -d downloads -m simple
Collecting vaa==0.2.1
  Using cached vaa-0.2.1-py3-none-any.whl (8.2 kB)
  Saved ./downloads/vaa-0.2.1-py3-none-any.whl
Successfully downloaded vaa
Failed to execute command 'create': error while processing 'downloads/vaa-0.2.1-py3-none-any.whl': invalid metadata file
To get further information re-run the script with --print-traceback
```

That downloaded wheel can be installed, unpacked and I ran it through  wheel-inspect and check-wheel-contents. The METADATA file itself I ran through rstcheck without error. So maybe the problem is with pypi-mirror handling the wheel?

I also the traceback :
```
pypi-mirror --print-traceback  create  -d downloads -m simple
Failed to execute command 'create': error while processing 'downloads/vaa-0.2.1-py3-none-any.whl': invalid metadata file
Traceback (most recent call last):
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 158, in get_pkg
    return Pkg(f, get_pkg_metadata(f))
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 149, in get_pkg_metadata
    metadata = getter(f)
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 98, in get_metadata_from_wheel
    metadata = parse_pkg_metadata(metadata)
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 68, in parse_pkg_metadata
    raise Exception('invalid metadata file')
Exception: invalid metadata file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 739, in main
    cmd.run(args)
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 546, in run
    create_mirror(args.download_dir, args.mirror_dir)
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 269, in create_mirror
    pkgs = pkgs if pkgs is not None else list_pkgs(download_dir, False)
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 211, in list_pkgs
    all_pkgs = [get_pkg(f) for f in list_dir(download_dir, test)]
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 211, in <listcomp>
    all_pkgs = [get_pkg(f) for f in list_dir(download_dir, test)]
  File "/home/rene/.local/share/virtualenvs/vaa-0dRp1FtJ/lib/python3.8/site-packages/pypi_mirror.py", line 160, in get_pkg
    raise Exception("error while processing '{}': {}".format(f, str(e)))
Exception: error while processing 'downloads/vaa-0.2.1-py3-none-any.whl': invalid metadata file

```

**Comment by montag451** [comment]
Hi @renefritze,

Thx for the bug report. I published a new version on PyPI (v4.0.4) that should fix your problem. I will close this issue as soon as you confirm that it is indeed the case.

**Comment by renefritze** [comment]
Thank you @montag451 for the quick fix (again!)! The vaa package is now processed correctly. 
However, I now get an error in the [deal package](https://pypi.org/project/deal/) (again missing homepage). Would you be OK with making the homepage/project url optional (falling back to blank string?) in your parser. It seems technically neither one of the fields is [required](https://packaging.python.org/specifications/core-metadata/).

**Comment by montag451** [comment]
You are right, this field is not required. I published a new version on PyPI (v4.0.5) which removes the need for a homepage field in the metadata file. Let me know if it fixes your problem :)

**Comment by renefritze** [comment]
Great, works for all the packages I have to mirror, thank you! You saved me quite a headache with the quick help today :tada:

**Comment by montag451** [comment]
You are welcome!
