### ISSUE TITLE
Errors with some packages, different behavior for pip<22 and pip >22

### ISSUE THREAD

**Issue by Barsovski** [montag451/pypi-mirror#18]
Hello!
With pip<22 using "pypi-mirror download" cause this error for small amount of packages. 
bayoo-docx==0.2.17 for example

```ERROR: Command errored out with exit status 1:
command: /home/anri/PycharmProjects/pip_server/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-8pofc930/bayoo-docx_61062f1f393549228085d59218078250/setup.py'"'"'; __file__='"'"'/tmp/pip-download-8pofc930/bayoo-docx_61062f1f393549228085d59218078250/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q5h65xf0
cwd: /tmp/pip-download-8pofc930/bayoo-docx_61062f1f393549228085d59218078250/
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-download-8pofc930/bayoo-docx_61062f1f393549228085d59218078250/setup.py", line 61, in <module>
LONG_DESCRIPTION = text_of('DESCRIPTION.rst') + '\n\n' + text_of('HISTORY.rst')
File "/tmp/pip-download-8pofc930/bayoo-docx_61062f1f393549228085d59218078250/setup.py", line 16, in text_of
with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-download-8pofc930/bayoo-docx_61062f1f393549228085d59218078250/DESCRIPTION.rst'
----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/89/be/65c320e7cef3182ca58367d1e470d77783223cf366499db4b01134b3ba65/bayoo-docx-0.2.17.tar.gz#sha256=be98a40a6e681a0117b7c4769008ffef4a7d0244699091faaa158e756cb17b9b (from https://pypi.org/simple/bayoo-docx/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement bayoo-docx==0.2.17 (from versions: 0.2.9b0, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16, 0.2.17)
ERROR: No matching distribution found for bayoo-docx==0.2.17
WARNING: You are using pip version 21.1; however, version 22.0.4 is available.
You should consider upgrading via the '/home/anri/PycharmProjects/pip_server/venv/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
File "/home/anri/PycharmProjects/pip_server/venv/lib/python3.8/site-packages/pypi_mirror.py", line 773, in main
cmd.run(args)
File "/home/anri/PycharmProjects/pip_server/venv/lib/python3.8/site-packages/pypi_mirror.py", line 553, in run
download_(pkgs, args.requirements)
File "/home/anri/PycharmProjects/pip_server/venv/lib/python3.8/site-packages/pypi_mirror.py", line 219, in download
subprocess.check_call(args)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'download', '-d', '/home/anri/PycharmProjects/pip_server/media/packages', '--no-binary', ':all:', 'bayoo-docx==0.2.17']' returned non-zero exit status 1.


```

With pip>22 this comand for bayoo-docx==0.2.17 cause this:

```
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-download-vtb1s0dl/bayoo-docx_06d081c380ba46339b925f4638a6f814/setup.py", line 61, in <module>
LONG_DESCRIPTION = text_of('DESCRIPTION.rst') + '\n\n' + text_of('HISTORY.rst')
File "/tmp/pip-download-vtb1s0dl/bayoo-docx_06d081c380ba46339b925f4638a6f814/setup.py", line 16, in text_of
with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-download-vtb1s0dl/bayoo-docx_06d081c380ba46339b925f4638a6f814/DESCRIPTION.rst'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
File "/home/anri/PycharmProjects/pip_server/venv/lib/python3.8/site-packages/pypi_mirror.py", line 773, in main
cmd.run(args)
File "/home/anri/PycharmProjects/pip_server/venv/lib/python3.8/site-packages/pypi_mirror.py", line 553, in run
download_(pkgs, args.requirements)
File "/home/anri/PycharmProjects/pip_server/venv/lib/python3.8/site-packages/pypi_mirror.py", line 219, in download
subprocess.check_call(args)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'download', '-d', '/home/anri/PycharmProjects/pip_server/media/packages', '--no-binary', ':all:', 'bayoo-docx==0.2.17']' returned non-zero exit status 1.
```

From console `pip install bayoo-docx==0.2.17` work correctly with all PIP versions

**Comment by montag451** [comment]
Hi @Barsovski,

You should try to use the `-b` flag of the `download` command. I think in the next release I will made it the default behavior.

**Comment by montag451** [comment]
No news is good news :smiley:
