### ISSUE TITLE
command "pypi-mirror --help" doesn't work like expected

### ISSUE THREAD

**Issue by winter1967** [montag451/pypi-mirror#2]
Hello,
i tried pypi-mirror on a centos7 system, using pyhton 2.7.5 and the newest pip Version. After installing it i try "pypi-mirror --help and got the following error:

`
root@pypiMirror ~]# pypi-mirror --help
Traceback (most recent call last):
  File "/usr/bin/pypi-mirror", line 9, in <module>
    load_entry_point('python-pypi-mirror==3.0.0', 'console_scripts', 'pypi-mirror')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pypi_mirror.py", line 54
    m = re.search(rb'^Name: (.*)$', metadata, re.MULTILINE)
                                 ^
SyntaxError: invalid syntax
`

The same error whatever i do with the command pypi-mirror.

**Comment by montag451** [comment]
Hi,

pypi-mirror works only with Python 3, it's the reason why you have this error.
